# Site settings
#
# Date of this Update to Config-template file ver 12-18-2017
#
# github: [metadata]
theme: "jekyll-theme-cayman"
# repository: https://www.github.com/rwebaz/Canna-Lessons-Project
title: "Canna Lessons Project"
tagline: "A Github repo of Canna Lessons and Articles that emphasize the GFM, Kramdown and Prince XML engines."
description: "A Github repo of Canna Lessons and Articles that emphasize the GFM, Kramdown and Prince XML engines."
twitter:
    username: "mminail"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github_username: "rwebaz"
    twitter_username: "rwebaz"
# The 'baseurl' is the subpath of your website, e.g. /blog
baseurl: "/Canna-Lessons-Project"
# The 'url' is the parental web address of your designated project, e.g. /https://rwebaz.github.io
url: "https://rwebaz.github.io"
exclude: ['README.md']
markdown: "kramdown"
highlighter: "rouge"
kramdown:
    input: "GFM"
    hard_wrap: "false"
    syntax_highlighter: "rouge"
    math_engine: "mathjax"
timezone: "America/Phoenix"
google_analytics: [UA-44765001-13]
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/png"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/svg"
    values:
      image: "true"
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "default"
      author: "Robert Weber, Director"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default" 
      author: "Robert Weber, Director"
collections:
  collection_CFFP:
    output: "true"
defaults:
  - scope:
      path: ""
      type: "collection_CFFP"
    values:
      layout: "page"
plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  