# Site settings
#
# github: [metadata]
theme: "jekyll-theme-cayman"
# repository: rwebaz/Canna-Lessons-Project
title: "Canna Lessons Project"
tagline: "A Github repo of Canna Lessons"
description: "A Github repo of Canna Lessons"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github_username: "mminail"
    twitter_username: "mminail"
# The 'baseurl' is the subpath of your website, e.g. /blog
baseurl: "/Canna-Lessons-Project"
url: "https://rwebaz.github.io"
exclude: ['README.md']
markdown: "kramdown"
highlighter: "rouge"
kramdown:
    input: "GFM"
    hard_wrap: "false"
    syntax_highlighter: "rouge"
    math_engine: "mathjax"
timezone: "America/Phoenix"
google_analytics: [UA-44765001-13]
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/ico"
    values:
      image: "true"
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "default"
      author: "Robert Weber, Director"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default" 
      author: "Robert Weber, Director"
collections:
  collection_CFFP:
    output: "true"
defaults:
  - scope:
      path: ""
      type: "collection_CFFP"
    values:
      layout: "page"
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock